### ISSUE TITLE
Choosing lossless mode would still crop in precise mode

### ISSUE THREAD

**Issue by royjor2016** [danmichaelo/croptool#170] opened 2022-01-12 11:38 UTC
i think, that it's been a while, that lossless mode has disappeared. choosing lossless is now actually the same as choosing precise.

my observations:

1. in the past, when previewing a crop of jpg in lossless, the dimension would often be augmented above and on the left, because jpgs are handled in 8x8  or 16x16 pixel blocks. now no matter how you wanna crop a jpg, the specified dimension would always be allowed, which could only be true in precise mode.
2. cropping files in https://commons.wikimedia.org/wiki/Category:Incomplete_files_(5_MB_interruption) in lossless mode used to end up in errors, but now it's possible, and resultant filesize is the same as a precise crop, e.g. https://commons.wikimedia.org/wiki/File:Dairy_Heifers_on_Pasture_.jpg .

**Comment by zanhecht** [comment] 2022-06-15 15:09
@danmichaelo Could this have been introduced by the refactor in September 2020? There's likely a large number of files on commons that are being silently damaged by this bug.

**Comment by Jonteemil** [comment] 2022-06-29 15:14
Duplicate of #163

**Comment by zanhecht** [comment] 2022-06-29 15:21
> Duplicate of #163

There may be a similar root cause, but it's not a duplicate. #163 is about GIFs and PNGs saying that impossible crop modes were used, this bug is about the fact that there is no way to actually do a lossless crop, and that no matter which mode CropTool says its using in the logs and edit comments, it's actually just passing the files to imagemagick to do a regular lossy crop.

**Comment by geofferb** [comment] 2024-03-28 07:03
Should be closed now #182 has been merged

**Closed** 2024-07-29 20:41 UTC
