### ISSUE TITLE
Watermark tag not removed

### ISSUE THREAD

**Issue by LTeles** [danmichaelo/croptool#47] opened 2015-05-29 00:29 UTC
Hi!

I had to manually remove watermark tag as CropTool didn't do it automatically.

https://commons.wikimedia.org/w/index.php?title=File%3AFloor_%28Revamp%29_em_S%C3%A3o_Paulo_%281%29.jpg&type=revision&diff=161994776&oldid=161994750

Regards.

**Comment by danmichaelo** [comment] 2015-06-06 19:55
I'm not sure if it's a good idea to have CropTool *always* remove this, since there might be cases where you do a crop, but can't remove the watermark. But I can add a checkbox (perhaps even checked by default) to remove {{watermark}}

**Comment by danmichaelo** [comment] 2015-06-07 22:25
Duplicate of #34

**Closed by danmichaelo** 2015-06-07 22:25 UTC

**Comment by danmichaelo** [comment] 2015-06-08 07:56
CropTool should now remove {{watermark}} : https://commons.wikimedia.org/w/index.php?title=File%3ALancia_delta_1.6_GTie_engine_2.jpg&type=revision&diff=162892937&oldid=162892935

**Comment by LTeles** [comment] 2015-06-08 23:52
Thanks!
