### ISSUE TITLE
PNG cannnot be cropped

### ISSUE THREAD

**Issue by peteforsyth** [danmichaelo/croptool#56] opened 2015-10-22 22:53 UTC
I have tried various crops on this file:
Thomas Condon from Centennial History of Oregon.png

They all produce:
[Error] Crop failed: Unknown error 1

There are a multitude of similar PNG files from this book, and similar books, that will all need cropping. If the PNG is too big, or something like that, is there a way to address that?

**Comment by danmichaelo** [comment] 2015-10-23 01:59
You got this error when pressing Preview, not Upload, right? Can you give it another try? I cannot reproduce the problem with this file right now, so I wonder if it might have been an intermittent issue.

**Comment by peteforsyth** [comment] 2015-10-28 01:46
Yes, at the "Preview" stage -- I don't get to upload. I just tried again on the same image, same problem. I'm using the latest Chrome on Windows 10 if that helps.

**Comment by peteforsyth** [comment] 2015-12-15 16:35
This issue also applies to the following file (and, I suspect, all similar files -- there are many portraits from this book I would like to crop.) Could it be that PNGs above a certain size cause problems? https://commons.wikimedia.org/wiki/File:Chief_Joseph_from_Centennial_History_of_Oregon.png

**Comment by peteforsyth** [comment] 2015-12-15 16:45
I tried two unrelated (and smaller) files, and had the same problem: https://commons.wikimedia.org/wiki/File:Jorge_Rafael_Videla.png https://commons.wikimedia.org/wiki/File:Fresh_mint_in_Fes,_Morocco.png

**Comment by danmichaelo** [comment] 2015-12-15 23:21
The strange part is that I still can't reproduce any of your examples. If it has something do with the PNG files themselves, you really wouldn't expect it to work for one user and not for another. I could try to add some more logging on the server to perhaps understand better what's going on, but I might not get that done before christmas :)

**Comment by peteforsyth** [comment] 2015-12-16 00:26
Weird! Can you actually crop one of those, to be sure it fully works for
you?

If it will help, I can experiment with different computers/browsers. I also
have another account I could try it with.

Thanks for your continued efforts! It's a great tool.

Pete

**Comment by danmichaelo** [comment] 2015-12-16 11:01
This worked: https://commons.wikimedia.org/wiki/File:Chief_Joseph_from_Centennial_History_of_Oregon.png

It would be interesting if you could test on different computers/browsers. Perhaps there is a subtle javascript bug somewhere that causes a successful response to interpreted as an error in some cases...

**Comment by danmichaelo** [comment] 2016-05-16 13:31
Any updates on this, @peteforsyth ? If not I have to close this as not reproducable

**Comment by peteforsyth** [comment] 2016-05-16 20:18
I'm sorry for the delay, Dan. It does seem to be a browser-related problem. I continue to have the problem with Chrome on Windows, but I just successfully used the tool in Firefox on Mac OS. If you'd like me to test browsers more thoroughly, let me know; I can't do thorough testing right away, but am happy to help if you can wait a couple days. If you can let me know what browsers you have already tried, that might save me some trouble.

But for my purposes, this is sufficient; if I need to use my Mac to accomplish the cropsI want to perform on PNGs, that's not a problem, now that I know what to do! Thanks again for your efforts on this.

**Comment by danmichaelo** [comment] 2016-05-20 18:33
No need, I just figured out the steps to reproduce :grin:

1. Do a lossless jpg crop. The preference for "lossless" is stored in cookie.
2. Do a png crop. It fails because lossless mode isn't supported/needed for png.

Such a prime example of how stored state can cause hard-to-catch bugs!

**Closed** 2016-05-20 19:04 UTC
