### ISSUE TITLE
Hangs on "Just a moment... waiting for the API to respond"

### ISSUE THREAD

**Issue by owcz** [danmichaelo/croptool#86] opened 2017-02-02 23:27 UTC
Not sure if the API/tool is down, but if this is up for several minutes, would it be better to gracefully timeout instead?

**Comment by danmichaelo** [comment] 2017-02-03 01:29
Perhaps. In any case, I restarted the tool now and it's working again, but it's still slower than it should be. When testing on my own computer, the first request takes about 0,5 seconds, but on Tool Labs it takes about 3 seconds. Seems like it's filesystem related.

**Comment by danmichaelo** [comment] 2017-02-13 20:07
Resolving this for now since the issue is officially solved. I will still try to see if there's things I can do to make the tool load faster in the future, or perhaps add a timeout.

**Closed by danmichaelo** 2017-02-13 20:07 UTC
